- name: Install additional packages
  apt:
    update_cache: true
    name:
      #- linux-modules-extra-raspi # for r8188eu driver
      - wireless-tools
      - net-tools

- name: Upgrade netplan for wext
  apt:
    name: netplan.io
    state: latest

