name: CI

on:
  push:
    branches:
      - "*"

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            extra-platforms = aarch64-linux

      - name: Cache store
        uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Install QEMU
        run: sudo apt install -y qemu-user-static

      - name: Check flake
        run: nix flake check
