name: CI

on:
  push:
    branches:
      - "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get tools
        run: make tools

      - name: Build image
        run: make image
